[package]
name = "portfolio-entity"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
chrono = "^0.4"
async-trait = "0.1.60"

[dependencies.sea-orm]
version = "^0.10"
