[package]
name = "portfolio-core"
version = "0.1.0"
edition = "2021"

[dependencies]
portfolio-entity = { path = "../entity" }
rand = "0.8.5"
argon2 = "0.4.1"
chrono = "0.4.22"

[dependencies.sea-orm]
version = "^0.10.0"
features = [
    "runtime-tokio-native-tls",
    "sqlx-postgres",
    "sqlx-sqlite",
]

[dev-dependencies]
tokio = "1.21.2"

[features]
mock = ["sea-orm/mock"]
